#ifndef VERSION_H
#define VERSION_H

// 全局唯一版本号
#define VERSION_MAJOR 4
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_STRING "V4.0"

// 内核版本
#define KERNEL_VERSION_MAJOR 4
#define KERNEL_VERSION_MINOR 0
#define KERNEL_VERSION_PATCH 0
#define KERNEL_VERSION_STRING "4.0.0"

// ABI版本
#define ABI_VERSION_MAJOR 4
#define ABI_VERSION_MINOR 0
#define ABI_VERSION_PATCH 0
#define ABI_VERSION_STRING "4.0.0"

// 接口版本
#define API_VERSION_MAJOR 4
#define API_VERSION_MINOR 0
#define API_VERSION_PATCH 0
#define API_VERSION_STRING "4.0.0"

// 构建信息
#define BUILD_DATE __DATE__
#define BUILD_TIME __TIME__

// 版本号组合
#define VERSION_CODE ((VERSION_MAJOR << 16) | (VERSION_MINOR << 8) | VERSION_PATCH)
#define KERNEL_VERSION_CODE ((KERNEL_VERSION_MAJOR << 16) | (KERNEL_VERSION_MINOR << 8) | KERNEL_VERSION_PATCH)
#define ABI_VERSION_CODE ((ABI_VERSION_MAJOR << 16) | (ABI_VERSION_MINOR << 8) | ABI_VERSION_PATCH)
#define API_VERSION_CODE ((API_VERSION_MAJOR << 16) | (API_VERSION_MINOR << 8) | API_VERSION_PATCH)

// 版本检查宏
#define VERSION_AT_LEAST(major, minor, patch) \
    (VERSION_MAJOR > (major) || \
     (VERSION_MAJOR == (major) && VERSION_MINOR > (minor)) || \
     (VERSION_MAJOR == (major) && VERSION_MINOR == (minor) && VERSION_PATCH >= (patch)))

#endif // VERSION_H